name: Sync this fork with the upstream repo
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Merge with upstream
        env:
          UPSTREAM_URL: https://github.com/gpakosz/.tmux.git
        run: |
          git remote add -f upstream "$UPSTREAM_URL"
          git remote -v
          git branch --all
          git config --list
          git config --local user.email "sync-upstream+bot@users.noreply.github.com"
          git config --local user.name "Sync Upsteam Bot"
          git merge upstream/master
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
